// Generated by gencpp from file serial_node/Serial.msg
// DO NOT EDIT!


#ifndef SERIAL_NODE_MESSAGE_SERIAL_H
#define SERIAL_NODE_MESSAGE_SERIAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial_node
{
template <class ContainerAllocator>
struct Serial_
{
  typedef Serial_<ContainerAllocator> Type;

  Serial_()
    : speed_rpm(0)
    , angle_degrees(0.0)  {
    }
  Serial_(const ContainerAllocator& _alloc)
    : speed_rpm(0)
    , angle_degrees(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _speed_rpm_type;
  _speed_rpm_type speed_rpm;

   typedef float _angle_degrees_type;
  _angle_degrees_type angle_degrees;




  typedef boost::shared_ptr< ::serial_node::Serial_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_node::Serial_<ContainerAllocator> const> ConstPtr;

}; // struct Serial_

typedef ::serial_node::Serial_<std::allocator<void> > Serial;

typedef boost::shared_ptr< ::serial_node::Serial > SerialPtr;
typedef boost::shared_ptr< ::serial_node::Serial const> SerialConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_node::Serial_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_node::Serial_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace serial_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'serial_node': ['/home/nvidia/catkin_ws/src/serial_node/msg'], 'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::serial_node::Serial_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_node::Serial_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_node::Serial_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_node::Serial_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_node::Serial_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_node::Serial_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_node::Serial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2369ae040ed10223d8b39ba1fe6713c2";
  }

  static const char* value(const ::serial_node::Serial_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2369ae040ed10223ULL;
  static const uint64_t static_value2 = 0xd8b39ba1fe6713c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_node::Serial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_node/Serial";
  }

  static const char* value(const ::serial_node::Serial_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_node::Serial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 speed_rpm\n\
float32 angle_degrees\n\
";
  }

  static const char* value(const ::serial_node::Serial_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_node::Serial_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed_rpm);
      stream.next(m.angle_degrees);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Serial_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_node::Serial_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_node::Serial_<ContainerAllocator>& v)
  {
    s << indent << "speed_rpm: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speed_rpm);
    s << indent << "angle_degrees: ";
    Printer<float>::stream(s, indent + "  ", v.angle_degrees);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_NODE_MESSAGE_SERIAL_H
